### ISSUE TITLE
Invalid cache key in action

### ISSUE THREAD

**Issue by TheSuperiorStanislav** [lewagon/wait-on-check-action#105]
https://github.com/lewagon/wait-on-check-action/blob/d538c0859f4ce2298db759b35e8b4df7baab4fa3/action.yml#L58

![image](https://github.com/lewagon/wait-on-check-action/assets/43534015/d3592dc1-e821-42d1-84c5-493441608396)

Is this intended? 
Maybe add normal key or at least `lewagon-wait-on-check-action` or something like that?

**Comment by JoelLefkowitz** [comment]
@TheSuperiorStanislav thank you for raising this issue.

The `restore-key` field is only used to retrieve caches, when a cache is saved it has its name set by the `key` field:

```yml
key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
```

For example, our most recent run generated this cache named: `Linux-gems-afd86d426e091aa4c07366c38a64266f0d58a53b0c38e6b1c80f636d90bb534e`

Could you please share the workflow that your screenshot came from so we can see why there's no hash included?

**Comment by TheSuperiorStanislav** [comment]
Here you go.

![Image](https://github.com/user-attachments/assets/69c7b81b-f3c1-4b4e-af11-c0169387146e)

Here also logs, which I probably should have attracted

![Image](https://github.com/user-attachments/assets/b078f5ab-3df2-48c2-a7b6-28583357e06b)

**Comment by TheSuperiorStanislav** [comment]
```yaml
name: Auto-merge approved automated PR
description: "Auto-merge approved automated PR if the number of approvals matches the expected."
inputs:
  expected-approvals:
    description: "Expected amount of approvals"
    default: "2"
    required: true
  workflow-name:
    description: "Name of workflow, what uses this action"
    required: true
  app-id:
    description: "App id which will merge PR"
    required: true
  app-private-key:
    description: "Private key of app which will create PR"
    required: true
runs:
  using: "composite"
  steps:
  - name: Generate token
    # Docs for action: https://github.com/marketplace/actions/github-app-token
    uses: tibdex/github-app-token@v2
    id: generate-token
    with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-private-key }}
  # Docs for action: https://github.com/marketplace/actions/wait-on-check
  - name: Wait for checks to succeed
    uses: lewagon/wait-on-check-action@v1.3.4
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      # To wait for all other checks to complete, set `running-workflow-name`
      # to the name of the current job https://github.com/marketplace/actions/wait-on-check#running-workflow-name
      running-workflow-name: ${{ inputs.workflow-name }}
      repo-token: ${{ steps.generate-token.outputs.token }}
      wait-interval: 10  # seconds
      allowed-conclusions: success,skipped
  - name: Merge pull request
    id: automerge
    # Docs for action: https://github.com/marketplace/actions/merge-pull-requests-automerge-action
    uses: pascalgn/automerge-action@v0.16.4
    env:
      MERGE_LABELS: automated-pr  # Defines which PR labels should be automatically merged
      MERGE_REQUIRED_APPROVALS: ${{ inputs.expected-approvals }}
      GITHUB_TOKEN:  ${{ steps.generate-token.outputs.token }}
  - if: steps.automerge.outputs.mergeResult == 'skipped'
    name: Feedback
    shell: bash
    run: |
      echo "Not enough approvals. Required: ${{ inputs.expected-approvals }}" >> $GITHUB_STEP_SUMMARY
```
