### ISSUE TITLE
doesn't work on branches

### ISSUE THREAD

**Issue by marten-seemann** [lewagon/wait-on-check-action#25]
The following workflow works fine if I run it on `master` (with `on: [ push, pull_request ]`), but it fails to detect any tests when running on the pull request branch. On that branch, it immediately returns, even though tests are still running.

```yml
on: [ pull_request ]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Wait on tests
      uses: lewagon/wait-on-check-action@master
      with:
        ref: ${{ github.sha }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        running-workflow-name: 'automerge' # HERE
    - name: Step to deploy
      run: echo 'success!'
```

Sample run: https://github.com/marten-seemann-test/target/runs/1940299479?check_suite_focus=true.
I assume this is because for some reason, it doesn't find any running tests:
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/1478487/108583818-4de3a880-7377-11eb-876b-c438420b7744.png">

Any ideas?

**Comment by marten-seemann** [comment]
After further debugging, the problem seems to be that for pull requests, GitHub is creating a (temporary) merge commit, and `github.sha` is the pointing to the sha of that merge commit, not the commit that triggered the build.

In order to wait for the tests of that PR to finish, one has to use `ref: ${{ github.event.pull_request.head.sha }}`.

I consider this issue resolved from a technical point, but maybe it would be helpful to explain this somewhere (in the README?).

**Comment by acostalima** [comment]
> After further debugging, the problem seems to be that for pull requests, GitHub is creating a (temporary) merge commit, and `${{ github.sha }}` is the pointing to the sha of that merge commit, not the commit that triggered the build.
> 
> In order to wait for the tests of that PR to finish, one has to use `ref: ${{ github.event.pull_request.head.sha }}`.
> 
> I consider this issue resolved from a technical point, but maybe it would be helpful to explain this somewhere (in the README?).

I can confirm this behavior on my end as well.

**Comment by progapandist** [comment]
Great! I'm totally down for updating the README to reflect that. Pop a quick PR and I'll merge it  🙏 
Hope it does not impact the rest of your workflows and you're still using this little action!

**Comment by acostalima** [comment]
@marten-seemann since you were the one to first report the issue, you'd you like to do the honors?

**Comment by jurgen-weber-deltatre** [comment]
I am trying to get this to work with a dependabot PR where it rebases if you commit to it everytime.

If I use the GH CLI, my PAT works using the branch name.

```
 $ gh pr checks dependabot/..../..../integrations/github-4.18.2
Some checks were not successful
2 failing, 0 successful, 0 skipped, and 0 pending checks

X  atlantis/plan
X  dependabot     51s  https://github.com/..../..../runs/4388834971?check_suite_focus=true
```

but this
```
The requested check was never run against this ref, exiting...
```

I have tried using the following as the ref:
github.event.pull_request.head.sha
github.head_ref
github.sha

**Comment by waylun** [comment]
@jurgen-weber-deltatre got the same issue today

**Comment by DaveSys911** [comment]
@marten-seemann Big thanks on posting the workaround
Should be added to the examples

**Comment by kpfleming** [comment]
The examples now use `${{ github.ref }}` instead of `${{ github.sha }}`; does that also address this issue?

**Comment by kpfleming** [comment]
... and the answer is no, that does not work. I now have this pair of steps in my workflow:

```yaml
    - name: ensure image has been created
      uses: lewagon/wait-on-check-action@v1.1.2
      if: github.event_name != 'pull_request'
      with:
        ref: ${{ github.sha }}
        check-name: image-hatch
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30
    - name: ensure image has been created
      uses: lewagon/wait-on-check-action@v1.1.2
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        check-name: image-hatch
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30
```
