### ISSUE TITLE
Support for timeout

### ISSUE THREAD

**Issue by Intrepidd** [lewagon/wait-on-check-action#26]
Hi ! 🇫🇷 

I am using this action to manually deploy my app, but I don't want to wait, I want to check for the completed status, and if it's ok, release, otherwise, fail.

I didn't manage to find an other existing action to do it, maybe you have suggestions ?

Otherwise, one "hack" could be to support a timeout, and in my case set it to a low value like 10 seconds.

WDYT ?

**Comment by progapandist** [comment]
Hi! Thanks for opening an issue. Can you please describe your case in more detail? What sort of "manual" deploy are we talking about?

**Comment by Intrepidd** [comment]
> What sort of "manual" deploy are we talking about?

My staging environment is auto-deployed
However, I don't want to autodeploy my prod environment and I want to choose when to deploy it.

I trigger a workflow manually [thanks to the workflow_dispatch event](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)

**Comment by matiasalbarello** [comment]
Hi @Intrepidd. I'm still not sure if I understood your case scenario. Are you using this action as a conditional to run other workflows? Could you share some examples (yml)? Thanks!

**Comment by Intrepidd** [comment]
Hi ! 

I use it as a condition to check my tests are green. Here is the beginning of my workflow :

```name: deploy
on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit ID to deploy
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Wait on tests
        timeout-minutes: 1
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.event.inputs.commit }}
          # check-name: specs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: 'deploy'
          wait-interval: 5

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0```


The idea is to only be able to deploy of the specs are green, otherwise fail immediately.

Thanks

**Comment by matiasalbarello** [comment]
Well, I think it's not functionality you should expect from this action but rather a feature you already have from GH Actions out of the box. If some of the checks that are being waited for end with a not allowed conclusion (see [allowed conclusions](https://github.com/lewagon/wait-on-check-action#allowed-conclusions)), then the whole action will fail. You can use this result to make further steps to not be executed, using `needs`. Using your example:
```yaml
on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit ID to deploy
        required: true

jobs:
  wait_for_tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Wait on tests
        timeout-minutes: 1
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.event.inputs.commit }}
          # check-name: specs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: 'deploy'
          wait-interval: 5
  deploy:
      - name: Do something
         description: Something that should only be executed if tests passed
         needs: wait_for_tests
         runs-on: ubuntu-20.04
         steps:
             .....
```
This way, `deploy` would only be executed if `wait_for_tests` succeeds, ergo, only if specs or any other tasks succeed.
