### ISSUE TITLE
Fails when not using `default` branch?

### ISSUE THREAD

**Issue by CWSites** [lewagon/wait-on-check-action#30]
I can't find anywhere in the documentation for this workflow which states that the default branch must be used. I updated my default to be `develop` and I am using this workflow on my `master` branch anytime there is a merge. Since making this change I am continuously getting the error `The requested check was never run against this ref`.

I have verified that the Dispatch job is using the same `SHA` as the Wait job is using.

## Dispatch Config
```yml
  verification:
    name: Dispatch - Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: run-lint-test-build
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
```

## Wait Config
```yml
name: Lint, Test & Build

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-lint-test-build]

jobs:
  verification:
    name: Lint, Format & Build # used for check-name on version.yml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - run: echo using SHA ${{ github.event.client_payload.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # https://github.com/marketplace/actions/yarn-install-cache
      - name: Cache yarn dependencies
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn install

      - name: Lint Code
        run: yarn lint

      - name: Code Format Check
        run: yarn format:check --verbose

      - name: Build
        run: yarn build
        env:
          CI: true
```

_Originally posted by @CWSites in https://github.com/lewagon/wait-on-check-action/issues/29#issuecomment-841305327_
