### ISSUE TITLE
Feature request: reduce outputs

### ISSUE THREAD

**Issue by cyanglaz** [lewagon/wait-on-check-action#31]
The wait-on-check produces a lot of outputs. Sometimes it made the GitHub web UI hang when trying to see the result. It would be nice to have a flag to make the output less verbose.
Maybe something like:
```
    - name: Wait on all tests
      uses: lewagon/wait-on-check-action@master
      with:
        ref: ${{ github.sha }}
        running-workflow-name: 'xxx'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 180 # seconds
        allowed-conclusions: success
        verbose: false
```

Maybe the output can just be like:
```
Waited for 312 seconds.
```
