### ISSUE TITLE
Feature request: Allow a list of check-names.

### ISSUE THREAD

**Issue by JoelLefkowitz** [lewagon/wait-on-check-action#35]
Currently you can specify a single job name with 'check-name' or you can wait for all checks to pass with 'running-workflow-name'. There are situations when you may want to wait for two jobs to complete in parallel before continuing.

**Comment by matiasalbarello** [comment]
Hi @JoelLefkowitz. I'll take a look.

**Comment by progapandist** [comment]
hey @matiasalbarello, thank you for coming back to the project :) I am actually leaving the company in a couple of months and will possibly have no time to keep maintaining this one (I haven't had any already, in months). would you like to take this repo up as a maintainer? For starters, would be great to actually release current master

of course it's fine if you're taken up too, then we can keep looking for maintainers.

**Comment by JoelLefkowitz** [comment]
> hey @matiasalbarello, thank you for coming back to the project :) I am actually leaving the company in a couple of months and will possibly have no time to keep maintaining this one (I haven't had any already, in months). would you like to take this repo up as a maintainer? For starters, would be great to actually release current master
> 
> of course it's fine if you're taken up too, then we can keep looking for maintainers.

I'm happy to be a maintainer too if you'd like

**Comment by progapandist** [comment]
That would be amazing. I will give you push access once I'm back at the computer. Super grateful there's interest to maintain this little project.

**Comment by matiasalbarello** [comment]
> hey @matiasalbarello, thank you for coming back to the project :) I am actually leaving the company in a couple of months and will possibly have no time to keep maintaining this one (I haven't had any already, in months). would you like to take this repo up as a maintainer? For starters, would be great to actually release current master
> 
> of course it's fine if you're taken up too, then we can keep looking for maintainers.

Hi @progapandist. Thanks for the consideration. But given the time I could dedicate to this project, I think I'll keep being just a Collaborator. I'll try to be around more frequently though.

**Comment by progapandist** [comment]
@JoelLefkowitz, I just invited you as a maintainer, welcome to the project and feel free to discuss everything with @matiasalbarello who contributed a very big deal to this repo and has probably the most expert opinion on the current project structure

**Comment by JoelLefkowitz** [comment]
> @JoelLefkowitz, I just invited you as a maintainer, welcome to the project and feel free to discuss everything with @matiasalbarello who contributed a very big deal to this repo and has probably the most expert opinion on the current project structure

Thanks @progapandist , will do.

**Comment by tamilselvanmp** [comment]
is it done? can we wait for one or more checks to complete?

**Comment by JoelLefkowitz** [comment]
@tamilselvanmp, this was not completed in the end. I will add this feature in an upcoming release 🚀

**Comment by matiasalbarello** [comment]
This Issue (and maybe many others) can be closed since GitHub provides a native solution:

Use `needs` with an array:
Current approach:
```
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Wait for specific jobs
          uses: lewagon/wait-on-check-action@v1.4.0
          with:
            check-names: ['frontend-tests', 'backend-tests']  # This doesn't exist
            repo-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Deploy
          run: ./deploy.sh
```
Native GitHub solution:
```
  jobs:
    frontend-tests:
      name: frontend-tests
      runs-on: ubuntu-latest
      steps:
        - name: Run frontend tests
          run: npm test

    backend-tests:
      name: backend-tests
      runs-on: ubuntu-latest
      steps:
        - name: Run backend tests
          run: python -m pytest

    integration-tests:
      name: integration-tests
      runs-on: ubuntu-latest
      steps:
        - name: Run integration tests
          run: ./integration-tests.sh

    deploy:
      needs: [frontend-tests, backend-tests]  # Wait for specific jobs only
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          run: ./deploy.sh
          # This runs ONLY after frontend-tests AND backend-tests complete
          # integration-tests can still be running - we don't wait for it
```

  1. No polling overhead - Instant execution when dependencies complete
  2. Parallel execution - Jobs run in parallel until deploy needs them
  3. Selective dependencies - Can choose exactly which jobs to wait for
  4. Visual dependency graph - GitHub UI shows clear job relationships
  5. Better error handling - Failed dependency jobs immediately fail dependent jobs
