### ISSUE TITLE
Couple usage/user questions

### ISSUE THREAD

**Issue by boldandbusted** [lewagon/wait-on-check-action#39]
Thanks for this Action. I have a couple questions:

* What is the purpose of 'wait-interval'? Does it have a default setting if it is unset?
* What is the timeout of this Action - or will it wait 'forever'?

Cheers! :)

P.S. Sorry, one more. Am I reading this Yaml right and seeing that the workflow is waiting on... itself? https://github.com/lewagon/wait-on-check-action/blob/master/.github/workflows/wait_omitting-check-name.yml

**Comment by matiasalbarello** [comment]
Hi @boldandbusted.
I'm sorry that the documentation is still a bit out of date regarding the features implemented.

Probably the most up to date documentation regarding the params is what you can find in the action.yml:
```yaml
inputs:
  ref:
    description: "A git ref to be checked: branch/tag/commit sha"
    required: true
  check-name:
    description: "A name of a check that has to pass"
    required: false
    default: ""
  check-regexp:
    description: "Filter checks to wait using Regexp"
    required: false
    default: ""
  repo-token:
    description: "A GitHub token for the repo"
    required: false
    default: ""
  wait-interval:
    description: "Seconds to wait between Checks API requests"
    required: false
    default: "10"
  running-workflow-name:
    description: "Name of the workflow to be ignored (the one who is waiting for the rest)"
    required: false
    default: ""
  allowed-conclusions:
    description: "Array of allowed conclusions"
    required: false
    default: success,skipped
```

And it can probably get improved.
- The `wait-interval` is the time between requests to the GitHub API to gather information from the running checks. 
- Regarding the timeout I'll take a look, I don't know it by heart. I can tell you that it doesn't wait forever 😅 

> P.S. Sorry, one more. Am I reading this Yaml right and seeing that the workflow is waiting on... itself? https://github.com/lewagon/wait-on-check-action/blob/master/.github/workflows/wait_omitting-check-name.yml

That specific action is waiting for all the rest since no name nor regexp was specified. The `running-workflow-name` param is actually to avoid the action waiting for itself in an infinite loop.

Hope it helped!
