### ISSUE TITLE
missing gemfile running on ubuntu 20.04.3

### ISSUE THREAD

**Issue by instil-ed** [lewagon/wait-on-check-action#49]
Hi, I've noticed wait-on-check-action started failing today (9/11). We run on ubuntu. The error output is:
```
Run bundle install
  bundle install
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Could not locate Gemfile

```

 I saw there was a merge today that might be a root cause, as I do notice the new logic that installs the bundle instead of running the dockerfile. Just to be sure, I also tried running the previously working sha (5e937358caba2c7876a2ee06e4a48d0664fe4967), and it worked. I'm not too familiar with ruby and how gemfiles work, so I'm a bit useless in regards to suggesting a fix here, but it would be much appreciated if you can help resolve the error for the handful of us ubuntu users. Thanks!

**Comment by matiasalbarello** [comment]
Could you share a sample of your workflow?

**Comment by instil-ed** [comment]
Sure, here's a snippet of the job. Thank you for taking a look!
```

  WaitForTestChecks:
    name: WaitForTestChecks
    runs-on: ubuntu-latest

    if:
      github.event_name == 'pull_request' &&
      github.event.action != 'closed'

    steps:
      - id: wait-for-tests
        name: Wait for tests
        uses: lewagon/wait-on-check-action@master
        with:
          running-workflow-name: WaitForTestChecks
          check-name: RunTests
          repo-token: ${{ secrets.TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          allowed-conclusions: success,skipped,cancelled
          wait-interval: 40
      - id: set-commit-status-to-success
        name: Set commit status to success
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          token: ${{ secrets.TOKEN }}
          name: RunTests
          status: success
          description: One or more test failed.
          url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
```
