### ISSUE TITLE
Error: The environment variable ImageOS must be set ruby/setup-ruby action

### ISSUE THREAD

**Issue by everspader** [lewagon/wait-on-check-action#52]
I'm running in the following error after the latest update of the action. 
I think it's related to [this](https://github.com/lewagon/wait-on-check-action/commit/315a64d9b7fd4d626bb4c1cdd4984351db862b97#diff-7314d0ebbd2e9537ae4889316745b4fd2fa43cb86275c9caae18a86ba228b642R19) in the new release.
because the [ruby-setup action](https://github.com/ruby/setup-ruby/blob/57d46d78b7d959dc4a248024a29bb17d4e357e5c/README.md#using-self-hosted-runners) requires the `ImageOS` to be set for self-hosted runners.
How can this be fixed?

### Error logging:
```
> Run lewagon/wait-on-check-action@master
  with:
    ref: bd8138c7d32e5e0296a3a4fa6f2a8ad080e4fd6d
    repo-token: ***
    check-name: Build base test image
    allowed-conclusions: success,skipped
    wait-interval: 10
    verbose: true
  env:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: postgres
> Run ruby/setup-ruby@v1.81.0
  with:
    ruby-version: 2.7
    bundler: default
    bundler-cache: false
    working-directory: .
    cache-version: 0
  env:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: postgres
/usr/bin/docker exec  e381481xxx sh -c "cat /etc/*release | grep ^ID"
Error: The environment variable ImageOS must be set
```

**Comment by matiasalbarello** [comment]
Hi @everspader, thanks for your report. Could you share your yaml?

**Comment by everspader** [comment]
This is my CI workflow. I'm currently using version `v1.0.0` and it works nicely but it breaks with `@master`. I have a similar workflow for building on my staging branch that didn't seem to be affected.
```yaml
name: project-ci

on:
  pull_request:

jobs:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      docker: ${{ steps.changes.outputs.docker }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check modified source
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            docker:
              - 'requirements.txt'

  build-test-image:
    needs: [detect-changes]
    name: Build base test image
    # Build a base docker image conditionally if previous job detected any change to requirements.txt
    # ...

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    container:
      image: <my_image_from_previous_job>
      credentials:
        username: <username>
        password: <password>

    steps:
      - name: Wait for base image to be built
        uses: lewagon/wait-on-check-action@1.0.0
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'Build base test image'
          allowed-conclusions: success,skipped

      - name: Checkout repository
        uses: actions/checkout@v2

     # ...
```
