### ISSUE TITLE
How to use this action to pause a job until the same job in previous workflow runs finished?

### ISSUE THREAD

**Issue by Alexander-Betz** [lewagon/wait-on-check-action#56]
Hello,

I have one workflow that might run in parallel multiple times (the same workflow file). I want a job in the workflow to wait until the same job in previous workflow runs finished. I thought I could use this action like that:
```
deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: main
          check-name: 'Deploy'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
```
But this results in all workflows being stuck (I assume because the job in the workflow is waiting for itself ?).

Can you tell me how I can pause a job until the same job in previous workflow runs finished with this action?
Or is the action only for jobs in different workflows?
If it's not working on a job level can I use it on a workflow level? So pause a workflow until previous workflow runs (same workflow file) finished?

I appreciate any answer and thank you in advance.
