### ISSUE TITLE
The requested check was never run against this ref, exiting...

### ISSUE THREAD

**Issue by ayozemr** [lewagon/wait-on-check-action#7]
Hello!

I am using your action to solve a problem I have:
- Workflow builds api on every push
- We want e2e workflow to run on PRs to master -> Runs using build artifact

So I set up a new workflow with your action, I used github.sha as ref because it runs in pushes to the PR.

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

name: Wait until build is complete
        uses: lewagon/wait-on-check-action@v0.1
        with:
          ref: ${{ github.sha }} # can be commit SHA or tag too
          check-name: build # name of the existing check - omit to wait for all checks
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 15 # seconds

I got this error. Maybe they triggered at the same time and e2e run before build job was started? I dont know if the correct way to implement it is to place some "sleep 15" before your wait on check 🤔 
`The requested check was never run against this ref, exiting...`

Thank you for your time!

**Comment by YonatanKra** [comment]
I get the same thing....

**Comment by rrijkse** [comment]
I solved this by running with `uses: lewagon/wait-on-check-action@master` haven't done a deep dive to figure out what's changed since the release but in my case it I was trying to use the feature from PR #6 which doesn't seem to be released yet.

**Comment by ayozemr** [comment]
> I solved this by running with `uses: lewagon/wait-on-check-action@master` haven't done a deep dive to figure out what's changed since the release but in my case it I was trying to use the feature from PR #6 which doesn't seem to be released yet.

Thanks @rrijkse , will try

**Comment by progapandist** [comment]
Let me know if it worked! I think I have to get serious about it and start a Changelog and regular release shedule, will be on it right after the New Year! For now using `master` is the best bet

**Comment by owen2345** [comment]
Hey here, I am having the same problem.
I have 3 testing workflows + 1 continuous deployment workflow.
After the first 3 workflows successfully completed, CD workflow "CD" is still stuck:
<img width="452" alt="Screen Shot 2021-01-07 at 6 06 13 AM" src="https://user-images.githubusercontent.com/1148415/103879910-d3a0e280-50ae-11eb-8a03-11aa676388d6.png">

**Hints**:
Maybe the checker is expecting for empty pending workflows but my CD workflow is still in progress, then it will never be processed.

**Comment by progapandist** [comment]
hi @owen2345 — can you please send me the example code from your workflow that uses the `wait-on-check`?

**Comment by owen2345** [comment]
Sure @progapandist 
```
name: Continous deployment

on:
  push:
    branches:
      - master
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # This step will retry until required check passes
      # and will fail the whole workflow if the check conclusion is not a success
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          # check-name: test # name of the existing check - omit to wait for all checks
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30 # seconds

      - name: Continuos deployment
        run: "..."

```
Please let me know if you need anything else to find the problem.
Thank you!
