### ISSUE TITLE
Not working with containers

### ISSUE THREAD

**Issue by ppamorim** [lewagon/wait-on-check-action#82]
The workflow below is not working with a `node` project in a container, please the sample code below:

```yml
name: Unit tests
on:
  pull_request:
    branches:
      - development

jobs:

  unit-test:
    #...

  dependency-check:
    #...

  upload-report:
    name: 🔨 Upload report
    runs-on: ubuntu-latest
    container: node:14.17.1-alpine3.12 #non alpine also doesn't work
    needs: [unit-test]
    timeout-minutes: 30
    env:
      ImageOS: ubuntu20 ## Stops error #52, not sure if this is right.

    if: "!contains(toJSON(github.event.head_commit.message), '[skip-ci]')"

    steps:

      - name: 🔨 Install dependencies
        run: apk add tar ruby # Ruby here makes no different

      - name: 📦 Download unit-test reports folder
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-unit-test

      # same error here:
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      #   with:
      #     ruby-version: '2.7'

      - name: 🕒 Wait for dependency-check to complete
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: 'dependency-check'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          
      - name: 📦 Download dependency-check reports folder
        uses: actions/download-artifact@v2
        with:
          name: dependency-check

```

It's returning this error:

```sh
Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/Ruby/2.7.4/x64/bin/gem'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/Ruby/2.7.4/x64/bin/gem ENOENT
```

![Screenshot 2023-02-14 at 19 14 19](https://user-images.githubusercontent.com/5521682/218834934-20424d3f-0c43-4ee5-a4fc-9d29ece6de3d.png)
