### ISSUE TITLE
Question: How do I use it from workflows executed in schedule

### ISSUE THREAD

**Issue by jparisu** [lewagon/wait-on-check-action#87]
Hi there,

I am trying to use this action in my CI project: https://github.com/jparisu/eProsima-CI/blob/56a5ca7399516d89c73f0bf95ba85e131ed842ca/.github/workflows/build_dev_utils.yml#L89
I have 2 workflows: A (build_fastdds) and B (build_dev_utils).
I want both to run in a schedule, so every night they run and upload updated artifacts.
But B requires of A artifact to run, so I want B to wait till A has finished.

I tried this in workflow B:
```
      - name: Wait for A workflow run to finish
        uses: jparisu/eProsima-CI/external/wait-on-check-action@main
        with:
          check-name: build_fastdds
          ref: main
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
But I get the following error: `The requested check was never run against this ref, exiting...`.
You can see a failing run here: https://github.com/jparisu/eProsima-CI/actions/runs/4785475063/jobs/8509467872

Thanks in advance
