### ISSUE TITLE
verbose:false not working

### ISSUE THREAD

**Issue by fallemand** [lewagon/wait-on-check-action#90]
This is my current setup: 
```
  - name: Wait for packages test/typecheck to complate
    uses: lewagon/wait-on-check-action@v1.3.1
    with:
      ref: ${{ github.ref }}
      check-regexp: packages-.*
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      wait-interval: 20
      verbose: false
```

But still, the action is printing everything.
