### ISSUE TITLE
Getting a 'Permission Denied' error with a simple use case

### ISSUE THREAD

**Issue by tking16** [lewagon/wait-on-check-action#92]
Error:
```
  Entries removed from PATH to avoid conflicts with default Ruby:
    /Users/automationm2mini/.rvm/gems/ruby-2.7.7-guacamole/bin
    /Users/automationm2mini/.rvm/gems/ruby-2.7.7-guacamole@global/bin
    /Users/automationm2mini/.rvm/rubies/ruby-2.7.7-guacamole/bin
  Entries added to PATH to use selected Ruby:
    /Users/runner/hostedtoolcache/Ruby/3.2.2/arm64/bin
Error: Error: EACCES: permission denied, mkdir '/Users/runner'
```

My Step:
```
      - name: Wait for APK to upload
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Upload apk'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
```
